import pandas as pd
df = pd.read_csv("netflix_titles.csv")
print(df.head())
print(df.info())
type_count = df["type"].value_counts()
print(type_count)
release_year_count = df["release_year"].value_counts().sort_index()
print(release_year_count)
country_count = df["country"].value_counts()
print(country_count.head(10))