import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("listings.csv")
print(df.head())
print(df.info())
print(df["price"].head(10))
print(df["price"].dtype)
df["price"] = df["price"].replace("[$,]", "", regex=True)
df["price"] = df["price"].astype(float)
print(df["price"].describe())
df_filtered = df[df["price"] < 500]
df_filtered["price"].hist(bins=50)
plt.title("Price distribution")
plt.xlabel("Price")
plt.ylabel("Count")
plt.savefig("Price_distribution.png", dpi=300, bbox_inches='tight')
plt.show()
room_price = df.groupby("room_type")["price"].mean()
room_price.plot(kind="bar")
plt.title("Average price by room type")
plt.xlabel("Room type")
plt.ylabel("Average price")
plt.savefig("Average_price_by_room_type.png",dpi=300, bbox_inches='tight')
plt.show()
df_filtered.boxplot(column="price",by="room_type")
plt.title("Price distribution by room type")
plt.suptitle("")
plt.xlabel("Room Type")
plt.ylabel("Price")
plt.savefig("Price_distribution_by_room_type.png",dpi=300, bbox_inches='tight')
plt.show()
area_price = df.groupby("neighbourhood_cleansed")["price"].mean()
area_price.plot(kind="bar")
plt.title("Price distribution by neighbourhood")
plt.xlabel("Neighbourhood")
plt.ylabel("Price")
plt.savefig("Price_distribution_by_nerighbourhood.png",dpi=300, bbox_inches='tight')
plt.show()